### ISSUE TITLE
ResourceHierarchyChecker False Positive

### ISSUE THREAD

**Issue by rennhard** [microsoft/restler-fuzzer#101]
Hello,

I think there's a bug with this checker that leads to false positives. The following sequence triggers a ResourceHierarchyChecker vulnerability:

This request creates **customer1**:

2020-12-04 11:03:13.322: Sending: 'PUT /Marketplace_vuln_fixed-rest/rest/customers/**customer1** HTTP/1.1\r\nAccept: application/json\r\nHost: 10.0.0.21:8080\r\nContent-Length: 0\r\nUser-Agent: restler/7.1.0\r\n\r\n'

2020-12-04 11:03:13.327: Received: 'HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 69\r\nX-Frame-Options: SAMEORIGIN\r\n\r\n{"customer":"**customer1**","password":"customer1","rolename":"customer"}'

This requests posts a message of **customer1** and returns the messageID of the new message (**12**):

2020-12-04 11:03:13.329: Sending: 'POST /Marketplace_vuln_fixed-rest/rest/customers/**customer1**/messages HTTP/1.1\r\nAccept: application/json\r\nHost: 10.0.0.21:8080\r\nContent-Type: application/json\r\nContent-Length: 30\r\nUser-Agent: restler/7.1.0\r\n\r\n{\n    "message":"customer1"}\r\n'

2020-12-04 11:03:13.341: Received: 'HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 61\r\nX-Frame-Options: SAMEORIGIN\r\n\r\n{"customer":"customer1","message":"customer1",**"messageID":12**}'

This accesses message **12** of **customer1**, which is legitimate:

2020-12-04 11:03:13.343: Sending: 'GET /Marketplace_vuln_fixed-rest/rest/customers/**customer1**/messages/**12** HTTP/1.1\r\nAccept: application/json\r\nHost: 10.0.0.21:8080\r\nContent-Length: 0\r\nUser-Agent: restler/7.1.0\r\n\r\n'

2020-12-04 11:03:13.351: Received: 'HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 61\r\nX-Frame-Options: SAMEORIGIN\r\n\r\n{"customer":"customer1","message":"customer1","messageID":12}'

However, this sequence triggers a ResourceHierarchyChecker vulnerability, which is a false positive.

Note that the fuzzer never uses another customer than customer1 in the final GET request (although I've added "customer2" to restler_fuzzable_string in dict.json).

Any help is appreciated, thanks a lot!

Marc

**Comment by PatGod** [comment]
@rennhard Hello, thank you for your feedback. What you describe looks indeed very strange. Specifically, we do not understand why the ResourceHierarchyChecker would ever flag the behavior above since message-ID=12 is a child of customerID=customer1 (the POST request you describe should establish this parent-child relation).

Could you please share with us the network logs and the ResourceHierarchyChecker output/logs so we can investigate?

Thanks much!

**Comment by rennhard** [comment]
Hi Patrice

I don't have the original logs anymore, but did another run, which shows the same behavior (now with messageID=10).

--Marc

[network.testing.140491490572032.1.txt](https://github.com/microsoft/restler-fuzzer/files/5645643/network.testing.140491490572032.1.txt)
[ResourceHierarchyChecker_20x_1.txt](https://github.com/microsoft/restler-fuzzer/files/5645644/ResourceHierarchyChecker_20x_1.txt)

**Comment by PatGod** [comment]
Hi Marc, thanks for the repro info. The checker output is interesting:

```
-> PUT /Marketplace_vuln_fixed-rest/rest/customers/customer1 HTTP/1.1\r\nAccept: application/json\r\nHost: 10.0.0.21:8080\r\n\r\n
! producer_timing_delay 0
! max_async_wait_time 20
PREVIOUS RESPONSE: 'HTTP/1.1 200 OK\r\nServer: Payara Server  5.201 #badassfish\r\nX-Powered-By: Servlet/4.0 JSP/2.3 (Payara Server  5.201 #badassfish Java/Oracle Corporation/11)\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: OPTIONS, GET, POST, PUT, DELETE\r\nAccess-Control-Allow-Headers: *\r\nContent-Type: application/json\r\nContent-Length: 69\r\nX-Frame-Options: SAMEORIGIN\r\n\r\n{"customer":"customer1","password":"customer1","rolename":"customer"}'

-> GET /Marketplace_vuln_fixed-rest/rest/customers/customer1/messages/10 HTTP/1.1\r\nAccept: application/json\r\nHost: 10.0.0.21:8080\r\n\r\n
! producer_timing_delay 0
! max_async_wait_time 20
PREVIOUS RESPONSE: 'HTTP/1.1 200 OK\r\nServer: Payara Server  5.201 #badassfish\r\nX-Powered-By: Servlet/4.0 JSP/2.3 (Payara Server  5.201 #badassfish Java/Oracle Corporation/11)\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: OPTIONS, GET, POST, PUT, DELETE\r\nAccess-Control-Allow-Headers: *\r\nContent-Type: application/json\r\nContent-Length: 61\r\nX-Frame-Options: SAMEORIGIN\r\n\r\n{"customer":"customer1","message":"customer1","messageID":10}'
```

The checker complains that the second GET request referring to resource messageID:10 is successful after executing only the first PUT request -- that is, without executing the POST request creating the resource messageID:10. 

Note that, in general, this is a real security bug and not a false alarm: if an attacker can guess a customerID and a message ID, it could access (GET) this message of that customer without being allowed to create (POST) messages for that customer. 

So the checker is doing its job in this case, even though this can be a false alarm in your particular context.

This alarm is probably triggered because the resource "customer1" is hard-coded and not cleaned up between fuzzing iterations/tests. 

If your service allows arbitrary strings as customer names (that is, not just customer1 and customer2), you can avoid these alarms by using randomly generated customer names. To do this, you need to add something like this in your fuzzing dictionary file: 

```
"restler_custom_payload_uuid4_suffix": {
    "customerID": "customer-",
```

so that your grammar will be changed so that 

`['customer1', 'customer2']`

is replaced by 

`+ restler_custom_payload_uuid4_suffix: customerID`

By using randomly generated customer names, this alarm will disappear.

Best,

Patrice

PS: @rifiles please have a look to confirm when you get a chance - thanks!

**Comment by rifiles** [comment]
@PatGod That description sounds perfect to me.

To add, for this example the customer1 / customer2 line will need to be updated to restler_custom_payload_uuid4_suffix('customerID') in the grammar (it's currently restler_fuzzable_string).

**Comment by rennhard** [comment]
Yes, this makes sense. I did another run with randomly generated customer IDs and the issue is not reported.

Thanks a lot, I'm closing the issue.
