### ISSUE TITLE
The request speed is slow

### ISSUE THREAD

**Issue by deepexplorer-web** [microsoft/restler-fuzzer#196]
I am trying to use restler to test some toy projects. However, I have found that restler could only send ~50-80 request per hour. Is it excepted? Or should I modify some settings to speed up restler?

**Comment by marina-p** [comment]
Hello @deepexplorer-web,

This is not expected.  Can you please share a few details about your setup:

- exact command line to RESTler.  
- version of python
- If possible, would you be able to share your 'Test' directory with all the logs, grammar etc.?  (If this reproduces in Test mode, or 'Fuzz' if fuzz mode)

**Comment by deepexplorer-web** [comment]
I am just following the documentation via https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/Fuzzing.md.
The specific command is: restler.exe fuzz --grammar_file <RESTLer grammar.py file> --dictionary_file <RESTler fuzzing-dictionary.json file> --time_budget <number_of_hours>

**Comment by PatGod** [comment]
The speed of execution of REST API requests is mostly determined by the service you test and by your socket/network connection, not by the speed of RESTler itself which is quite fast. 

For instance, try running RESTler with the DemoServer local service that comes with RESTler (see https://github.com/microsoft/restler-fuzzer/tree/main/demo_server ) -- what RESTler/request-by-minute speed do you see? (It should much faster than the speed you report.)

**Comment by deepexplorer-web** [comment]
Hi @PatGod, I have tried with your suggestions on the official demo of swagger - PetStore (https://hub.docker.com/r/swaggerapi/petstore). However, restler only totally sent ~1900 requests in one hour. The information attached as follows.

2021-05-04 15:40:12.475: Total Creations of Dyn Objects: 164
2021-05-04 15:40:12.475: Total Requests Sent: {'gc': 164, 'main_driver': 1900, 'LeakageRuleChecker': 0, 'ResourceHierarchyChecker': 0, 'UseAfterFreeChecker': 1, 'InvalidDynamicObjectChecker': 12, 'PayloadBodyChecker': 1414, 'ExamplesChecker': 0}
2021-05-04 15:40:12.475: Bug Buckets: {'InvalidDynamicObjectChecker_20x': 2, 'PayloadBodyChecker_500': 96}

**Comment by PatGod** [comment]
In your experiment above, RESTler sent 1900 + 164 + 1+ 12 + 1414 requests (thus, way more than 1900). If this experiment took ~1h, this is about 1 request/second. Again, this speed is due to the service under test and your socket/network connection.

My suggestion was to try RESTler on https://github.com/microsoft/restler-fuzzer/tree/main/demo_server which runs locally -- you should experience RESTler's maximum speed with this example in fuzz mode.

If you experience slower speeds with other services, it is because of the service under test and/or your network connection.
