### ISSUE TITLE
Further explanation of runsummary

### ISSUE THREAD

**Issue by Mafti** [microsoft/restler-fuzzer#199]
Hi,

I am not sure if I understand the runSummary.
requestCount, is this the total count of requests which have been done? (it seems, it only contains the failed requests?)
Because, when I look in testing_summary, i see different numbers?
In simple terms.

where can I find:
-  the total request done,
- number of requests with a 200 :)

**Comment by PatGod** [comment]
Hi @Mafti ,
The file testing_summary.json contains the information you want.

For instance, in the following example
```
{
    "final_spec_coverage": "9 / 16",
    "rendered_requests": "16 / 16",
    "rendered_requests_valid_status": "9 / 16",
    "num_fully_valid": 9,
    "num_sequence_failures": 0,
    "num_invalid_by_failed_resource_creations": 0,
    "total_object_creations": 42,
    "total_requests_sent": {
        "gc": 24,
        "main_driver": 28,
        "LeakageRuleChecker": 0,
        "ResourceHierarchyChecker": 4,
        "UseAfterFreeChecker": 2,
        "InvalidDynamicObjectChecker": 107,
        "PayloadBodyChecker": 0,
        "ExamplesChecker": 0
    },
    "bug_buckets": {
        "InvalidDynamicObjectChecker_20x": 5,
        "ResourceHierarchyChecker_20x": 1,
        "UseAfterFreeChecker_20x": 1
    }
}
```
num_fully_valid is the number of successfully 20x executed request types in your API.
total_requests_sent is the list of all requests sent, where "gc" is the RESTler garbage collector, main_driver is the core RESTler test engine, and the rest are requests sent by the various checkers that are turned on.

resultsAnayzer is an optional prototype post-processing tool that reads in the RESTler network.testing logs, and then counts and bucketizes requests in these logs using the request responses. Because this tool parses raw strings in the network logs, it can be flaky at times.

**Comment by marina-p** [comment]
Hello @Mafti,

The number in runSummary contains only failing requests, it should be named 'failingRequestCount' - we will fix this shortly.

**Comment by Mafti** [comment]
Thanks!

**Comment by mbiuki** [comment]
Is  "rendered_requests_valid_status" same as "num_fully_valid"?
For better understanding, could the information in summary logs, e.g. `testing_summary.json`, be documented. I have the same confusion as to interpret the results' value. Thanks.

**Comment by rifiles** [comment]
@mbiuki Hi Mehdi, num_fully_valid differs from rendered_requests_valid_status slightly:

"Valid status" simply means a status code was returned as valid (typically 2xx unless custom valid codes were set). 

"Fully valid" means there were no failures detected with the request at all. An example of a non-fully-valid request would be if there was a failure reported during an asynchronous resource creation.

**Comment by marina-p** [comment]
Thanks @rifiles!

Reopening to add documentation.

**Comment by mbiuki** [comment]
> @mbiuki Hi Mehdi, num_fully_valid differs from rendered_requests_valid_status slightly:
> 
> "Valid status" simply means a status code was returned as valid (typically 2xx unless custom valid codes were set).
> 
> "Fully valid" means there were no failures detected with the request at all. An example of a non-fully-valid request would be if there was a failure reported during an asynchronous resource creation.

@rifiles, thanks for your answer. So, would `num_fully_valid ` mean all allowable REST API for an endpoint are executed (based on spec file) without finding an error?

To put in the full picture, could you please also provide definitions for the following:

```
    "final_spec_coverage": Is it total number of REST APIs covered with or w/o 2xx?
    "rendered_requests": Is it total number of valid and invalid requests by PUT/POST?
    "rendered_requests_valid_status": Is it same as rendered_requests but only 201 ones?
    "num_fully_valid": Is it as explained above?
    "num_sequence_failures": Is it number of PUT/POST/GET/DELETE sequences that failed to happen?
    "num_invalid_by_failed_resource_creations": Not sure what this means?
    "total_object_creations": Is it total objects created by POST?
    "total_requests_sent":
        "gc": Is it the number of garbage collectors released objects?
        "main_driver": Is it total number of REST requests sent by the main RESTler engine?
        "LeakageRuleChecker":  Is it total number of REST requests sent to check this active checker?
        "ResourceHierarchyChecker": same as above?
        ...
 
    "bug_buckets": 
        "InvalidDynamicObjectChecker_20x": Is it invalid return code concluded by invalid dynamic object checker logic?
        "ResourceHierarchyChecker_20x": Is it same as above?
        "UseAfterFreeChecker_20x":  Same as above.
```

**Comment by PatGod** [comment]
> So, would num_fully_valid mean all allowable REST API for an endpoint are executed (based on spec file) without finding an error?


yes.

"final_spec_coverage" is the number of valid requests over the total number of requests (see the documentation).
"rendered_requests" is the number of requested attempted to be rendered/executed by RESTler (that is, the number of unique requests you will see being tried/executed in the network logs).
"num_sequence_failures" is the number of invalid requests due to a failure occurring when creating parent resources to that request.
"num_invalid_by_failed_resource_creations" is the number of invalid requests due to a failure when attempting to create the corresponding target resource type.
"total_object_creations" is the total number of objects (=resources) being created.
"InvalidDynamicObjectChecker_20x" is the number of bugs (=bug-buckets) found by the InvalidDynamicObjectChecker and which returned a 20x HTTP(s) status-code.

The other fields are similar or already explained above.
