### ISSUE TITLE
Openapi specs for Testing Restler on Gitlab-ee

### ISSUE THREAD

**Issue by victomteng1997** [microsoft/restler-fuzzer#210]
I am reading the four papers on the main page, and I saw that one of the testcases is on Gitlab. It is mentioned that the Gitlab API is at: https://docs.gitlab.com/ee/api/
Though the api documentation is well-defined for Gitlab, I didn't see any specs defined in openapi (swagger) format. Since Restler takes openapi format as input, may I know how to convert the web api documentation into openapi format? Or are there any resources available for me to download the openapi format specs for Gitlab?

**Comment by PatGod** [comment]
GitLab was one of the first big services we tested and fuzzed with RESTler. But that work was done almost 3 years ago, and both GitLab and RESTler have evolved **a lot** since then. Back then, in order to use RESTler on the GitLab REST APIs, we had to significantly modify manually the RESTler-generated grammar (but the RESTler compiler was also very primitive back then).

For an (up-to-date) OpenAPI spec of the GitLab REST API, please contact the GitLab support team.

**Comment by PatGod** [comment]
I am closing this issue since this is really a GitLab question.

**Comment by marina-p** [comment]
We are not aware of official OpenAPI specs for gitlab.  At the time, for our experiments it was a combination of using unofficial specs and patching the grammar when there were discrepancies with the service.

**Comment by victomteng1997** [comment]
Understood. Thanks for that!
