### ISSUE TITLE
Replay from network log? 

### ISSUE THREAD

**Issue by wilsondy** [microsoft/restler-fuzzer#354]
Quick question:  Is it possible to replay from the bare network log (or otherwise?). I've seen you can replay from a bug bucket.

**Comment by PatGod** [comment]
Since RESTler is an automatic test generation tool, the only support for replay is the replay mode for bugs found.

Since RESTler is fairly deterministic (even when fuzzing), you can also re-run the same test/fuzz-lean/fuzz RESTler job and you  are likely to get similar results, provided the service under test is itself deterministic.

You can also use the --path_regex option to focus RESTler to generate tests on a specific part of an API -- this is a way to 'replay' part of a large job on a specific sub-API.

And, of course, you can examine the network.testing logs, and then try to manually replay specific request sequences using other tools for manual testing, like curl, postman, etc.

**Comment by PatGod** [comment]
PS: you could also try to craft your own RESTler replay files by manually copy/pasting from the network.testing logs.

**Comment by marina-p** [comment]
Hello @wilsondy,

Closing this issue since the question is answered above.  Please let us know if you have further feedback on this use case.

Thanks,

Marina
