### ISSUE TITLE
ERROR: Results analyzer for logs in Fuzz fails

### ISSUE THREAD

**Issue by juliabennett-msft** [microsoft/restler-fuzzer#709]
### Description

Fuzz-lean worked for me, but Fuzz fails with the following error.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/127248428/223851201-afdc283f-b7e9-46ff-ba38-5ca694be64f6.png)

**Comment by marina-p** [comment]
Hello @juliabennett-msft,

Can you repeatedly run ```fuzz-lean``` successfully?  One possibility is that there is some corruption/leftover state from ```fuzz-lean``` in your environment that is causing ```fuzz``` to fail.  

It would be helpful if you could share the beginning of the network log (network.testing.*.txt) from both runs for further investigation.

Thanks,

Marina

**Comment by juliabennett-msft** [comment]
I retried fuzz-lean and it fails

**Comment by juliabennett-msft** [comment]
Where can I find the network.testing files?

**Comment by marina-p** [comment]
They are in RestlerResults\experiment*\logs

**Comment by juliabennett-msft** [comment]
Re: One possibility is that there is some corruption/leftover state from fuzz-lean in your environment that is causing fuzz to fail.

Is there a way for me to do a clean somehow?

**Comment by marina-p** [comment]
Hi Julia,

This issue is not with fuzzing, it is with parsing the network logs after fuzzing has completed.  I am going to close this issue since it is already being tracked by #465.

On a separate note, in these runs your RESTler setup is missing custom payloads for the {subscriptionId} and {resourceGroupName} parameters (and possibly others).  A coverage of 0/X often means that your API is not being reached due to some setup issue.  You need to investigate the results (in speccov.json, the network logs, or the new coverage_failures_to_investigate.txt report) and improve the coverage before running fuzz-lean and fuzz modes.

Thanks,

Marina

**Comment by juliabennett-msft** [comment]
[like]  Julia Bennett reacted to your message:
________________________________
