### ISSUE TITLE
Add ability to disable sensitive data logging in restler (e.g. full network log)

### ISSUE THREAD

**Issue by rifiles** [microsoft/restler-fuzzer#73]
Add the ability to disable logging in restler that could lead to leaked personal or sensitive information. I.e. request/response data sent to and received from the server.

**Comment by marina-p** [comment]
To clarify further: this option was proposed for the use case where the user has a RESTler setup where --logsUploadRootDirPath is set, and wants to avoid storing raw network logs.  This primarily applies for cases where RESTler may not be filtering authentication information (e.g. if added in custom headers).   

However, wouldn't any bug bucket contain a replay log with the sent request, which would contain the above data?

**Comment by PatGod** [comment]
Yes, this work item sounds ill-defined. RESTler and the Swagger spec define request going in and the service under test defines what is contained in responses. The RESTler is already in full control of where to store (or keep) network logs. (And telemetry does not include any network traffic.) So what is this item about? Please clarify (possibly with a clear scenario or example). Otherwise, I suggest to close this item.

**Comment by rifiles** [comment]
> To clarify further: this option was proposed for the use case where the user has a RESTler setup where --logsUploadRootDirPath is set, and wants to avoid storing raw network logs. This primarily applies for cases where RESTler may not be filtering authentication information (e.g. if added in custom headers).
> 
> However, wouldn't any bug bucket contain a replay log with the sent request, which would contain the above data?

The replay log does indeed contain this data, however the creation of the log could be disabled while still performing the replay, if desired.

**Comment by marina-p** [comment]
Closing this as out-of-scope for RESTler.  Such clean-up/log management can be done by the agent or user that invokes RESTler.
