### ISSUE TITLE
PayloadBodyChecker documentation

### ISSUE THREAD

**Issue by JoshuaEN** [microsoft/restler-fuzzer#94]
Hello,

The PayloadBodyChecker appears to have a number of undocumented options (looking at the source code). It would be helpful to have these options documented, including the recipe file.

Use-case:

In my testing, it appears that the default settings for the payload body checker result in trying a low number of payload combinations, often ever sending a single value for most of the body parameters.

While it is often infeasible to try every possible combination, my thought it would be good to try a few fuzzed values for each parameter.

It appears to be possible to have the checker try more combinations via the settings. For example, [this recipe](https://github.com/JoshuaEN/restler-fuzzer-testing/blob/main/Server/restler-fuzzer/inputs/payload_body_recipe.json) does try other values for all of the body parameters, but it is too far in the other direction (making ~12000 requests vs. 58 with the defaults) and it could still just be exhaustively checking up to a (much higher) limit.

Thus, having the settings documented would be helpful.

Thanks!

**Comment by PatGod** [comment]
@JoshuaEN Thank you for your feedback. The algorithms and techniques used in the PayloadBodyChecker are described in this paper: Intelligent REST API Data Fuzzing​​ (FSE'2020) https://patricegodefroid.github.io/public_psfiles/fse2020.pdf

Most of this checker's settings are discussed in that paper. 

Since there are many(!) possible setting configurations, the default settings roughly match what was found as the 'optimal' combination in the study described in that paper. But many other settings are indeed possible.

(Minimally, we should clarify the points above in the on-line documentation...)

Just out of curiosity, did you find more bugs with your custom recipe compared to the default one for your API/service under test? 

Thanks again!

**Comment by JoshuaEN** [comment]
@PatGod Thank you for the link, it was very helpful in understanding not just what features are available, but why they are useful.

> Just out of curiosity, did you find more bugs with your custom recipe compared to the default one for your API/service under test?

No. I tried the default, the recipe I linked (which I now realize is rather flawed), and a few others built around the recommendations from that document with larger `value_max_combination` values. None found any bugs in the API I'm testing.

Having read the document, it is now my understanding that the payload body checker's intent is not to do valid value fuzzing (e.g. trying different valid values for an enum parameter), which is what I was trying to do.

Thanks again for your help!
