### ISSUE TITLE
[Question] RESTler's Fuzzing "Goal"?

### ISSUE THREAD

**Issue by JoshuaEN** [microsoft/restler-fuzzer#99]
Hello,

I am wondering what the "goal" is for RESTler's fuzzing functionality: In general terms, is RESTler is intended to replace, or supplement, other HTTP fuzzing tools?

My understanding is its the former (replace), but I wanted to confirm.

Thanks!

---

For context, here are some examples that seem like gaps in fuzzing:
1. Valid parameter combinations are not fuzzed for endpoints with `examples`
1. Valid (based on isRequired) and invalid subsets of query parameters are not fuzzed (all query parameters defined in the grammar are always sent when fuzzing)
1. Randomized parameter values (e.g. random bit flipping, picking values from the fuzzing dictionary randomly, picking request candidate combinations randomly)
1. Brute force parameter values
1. General HTTP fuzzing (e.g. incorrect/missing headers, malformed/wrong content types for request bodies, etc...)

As a note, my only hands-on experience with fuzzing is through RESTler, so it is possible my expectations for what an HTTP fuzzer should do (what is valuable) are incorrect.

---

P.S. I saw [this question](https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/FAQ.md#q-what-is-the-difference-between-restler-and-web-scanners) in the FAQ, but "web scanners" appears to be a much broader field than just fuzzing.

**Comment by PatGod** [comment]
@JoshuaEN Thanks for your feedback. RESTler is not meant to replace web-scanners (looking for SQL injections, XSS attacks, etc.) or 'manual/interactive' testing tools like curl or Postman. See also the comment in "Systematic bug hunting over unit testing" in the "design Principles" of https://github.com/microsoft/restler-fuzzer/blob/main/docs/contributor-guide/Contributing.md 

Fuzzing means automatic test generation and execution with the goal of finding bugs. That's the goal of RESTler as a REST API fuzzer.

And since there are astronomically many ways to fuzz REST API requests, another important goal of RESTler is to perform fuzzing "intelligently": generate as few tests as possible while finding as many bugs as possible. 

When writing your comments starting with "for context...", are you referring to trying RESTler in fuzz-lean and/or fuzz mode, and with all the checkers on?

Regarding your points 3 (pure random fuzzing) and 4 (brute force enumeration of parameter values, like enumerating all possible integer values etc.), those are not priorities because the cost of these naive fuzzing techniques is clear (astronomical) but the value is near zero in the context of REST APIs in our experience so far (the probability of finding bugs this way is extremely low). However, if you disagree or want to do this anyways, you can instruct RESTler to do this if you want, by providing your own fuzzing dictionaries (possibly including many values combinations which RESTler will then systematically try).

Regarding your point 5, RESTler does fuzz both the path and bodies of requests (see also the next point below). Headers are indeed not fuzzed, as other tools (like HTTP web-scanners) already do this.

For your point 2, RESTler already does this for JSON body payloads of REST API requests - see the Payloadbody checker and this paper [Intelligent REST API Data Fuzzing](https://patricegodefroid.github.io/public_psfiles/fse2020.pdf)​​ (FSE'2020). But it is true that RESTler's fuzzing capabilities for *query* parameters is currently more limited - this is definitely an area of possible improvement. (Your detailed suggestions are welcome here.)

Regarding your point 1, I don't understand what you mean by "endpoints with examples" - RESTler already has an examples checker. Could you please clarify and/or give us a concrete example?

Thanks!

**Comment by JoshuaEN** [comment]
@PatGod thank you for the detailed response! "another important goal of RESTler is to perform fuzzing 'intelligently'" in particular gives me a clearer picture of what is in scope.

---

> When writing your comments starting with "for context...", are you referring to trying RESTler in fuzz-lean and/or fuzz mode, and with all the checkers on?

These were observed in fuzz mode, with all checkers on.

---

> Regarding your point 1, I don't understand what you mean by "endpoints with examples" - RESTler already has an examples checker. Could you please clarify and/or give us a concrete example?

When an endpoint has "x-ms-examples"/"examples" provided, the fuzzing RESTler's runner normally does (trying candidate combinations [of parameters], up to max_combinations) no longer happens for that endpoint.

[Here is an example run](https://github.com/JoshuaEN/restler-fuzzer-testing/tree/example/examples-fuzzing/Server/restler-fuzzer/results): The runner (not the checkers) only sends the example with no fuzzing for [`/api/v1/PayloadWithExamples`](https://github.com/JoshuaEN/restler-fuzzer-testing/blob/example/examples-fuzzing/Server/Controllers/PayloadWithExampleController.cs), where [`/api/v1/Payloads`](https://github.com/JoshuaEN/restler-fuzzer-testing/blob/example/examples-fuzzing/Server/Controllers/PayloadController.cs) shows the behavior I expect (of the runner trying 6 candidate combinations, due to `max_combinations`).

My expectation is the parameters present in the example would still be fuzzed (perhaps by the ExampleChecker) in a similar way to how endpoints without examples have theirs fuzzed.

To be clear, in both cases, the PayloadBodyChecker does fuzz, but my understanding is it focuses on fuzzing with structural/data type changes, verus fuzzing combinations of valid values (within a fuzzable group).

Also, the example checker does send all of the example requests, but it appears to only send the examples exactly as defined (the values of the parameters in the example are not fuzzed).

---

> For your point 2[...] it is true that RESTler's fuzzing capabilities for query parameters is currently more limited - this is definitely an area of possible improvement. 

Yes, I was specifically referring to query parameters, sorry if that was not clear.

Re suggestions, my initial thought is that the general concepts that apply to the body (from PayloadBodyChecker) seem to also apply to the query parameters.

Changing a parameter's type (perhaps including common syntaxes for arrays / objects, e.g. `ex[]=value`, `ex[0]=value`, `ex[key]=value`), duplicating a parameter (which could be part of changing type, since that is another approach to represent arrays), and sending subsets of all possible parameters all seem useful for a fuzzing a query string.

The other thing that comes to mind is invalid syntax (e.g. `?exA=value?exB=valueB`), but I suspect that would be covered by web-scanners.

---

> Regarding your points 3 (pure random fuzzing) and 4 (brute force enumeration of parameter values, like enumerating all possible integer values etc.), those are not priorities because the cost of these naive fuzzing techniques is clear (astronomical) but the value is near zero in the context of REST APIs in our experience so far (the probability of finding bugs this way is extremely low).

This makes sense given the goal of intelligent fuzzing, thanks!

I also realized "random-walk" appears to do one of the main things I was looking for (it picks request candidate combinations at random, rather than sequentially, and thus tries more combinations for an endpoint over the span of the run than "max_combinations" would otherwise allow).

---

Thank you again for the detailed reply!

**Comment by PatGod** [comment]
@JoshuaEN Thank you for your detailed reply. What you write is correct, so I won't comment further.

There may be two new action items coming out of this discussion:
(1) how to extend the payloadbody checker to fuzz query parameters? (or create a new QueryParameter checker)
(2) revisit how examples are handled by RESTler in fuzz mode

We'll keep these in mind...

**Comment by JoshuaEN** [comment]
@PatGod Thanks for following up and taking my suggestions into consideration!

Closing this since my original question was answered.
